#!/bin/bash

export DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG
export USER_COMMAND=$USER_COMMAND
export USER_SU=$USER_SU
export DRONE_S3_REGION=$DRONE_S3_REGION
export DRONE_S3_BUCKET=$DRONE_S3_BUCKET
export DRONE_S3_ACCESS_KEY=$DRONE_S3_ACCESS_KEY
export DRONE_S3_SECRET_KEY=$DRONE_S3_SECRET_KEY
export DRONE_S3_SOURCE=$DRONE_S3_SOURCE
export DRONE_S3_TARGET=$DRONE_S3_TARGET

bash .drone.yml.sh

drone exec --trusted --deploy
